-- TaskFlow schema, version 1.
-- Conventions: UUID primary keys generated by the application, timestamptz for instants,
-- enums stored as varchar guarded by CHECK constraints, and an index on every foreign key column.

CREATE TABLE users (
    id            uuid         PRIMARY KEY,
    name          varchar(100) NOT NULL,
    email         varchar(254) NOT NULL,
    password_hash varchar(100) NOT NULL,
    role          varchar(20)  NOT NULL,
    status        varchar(20)  NOT NULL DEFAULT 'ACTIVE',
    job_title     varchar(100),
    avatar        varchar(500),
    created_at    timestamptz  NOT NULL,
    updated_at    timestamptz  NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_lowercase CHECK (email = lower(email)),
    CONSTRAINT ck_users_role CHECK (role IN ('IT_MANAGER', 'PROJECT_OWNER', 'MEMBER')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DEACTIVATED'))
);

CREATE TABLE refresh_tokens (
    id          uuid        PRIMARY KEY,
    user_id     uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  varchar(64) NOT NULL,
    expires_at  timestamptz NOT NULL,
    created_at  timestamptz NOT NULL,
    revoked_at  timestamptz,
    replaced_by uuid,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash)
);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens (expires_at);

CREATE TABLE password_reset_tokens (
    id         uuid        PRIMARY KEY,
    user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    used_at    timestamptz,
    CONSTRAINT uk_password_reset_tokens_hash UNIQUE (token_hash)
);
CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id);
CREATE INDEX idx_password_reset_tokens_expires ON password_reset_tokens (expires_at);

CREATE TABLE projects (
    id          uuid          PRIMARY KEY,
    name        varchar(100)  NOT NULL,
    description varchar(2000),
    owner_id    uuid          NOT NULL REFERENCES users (id),
    created_at  timestamptz   NOT NULL,
    updated_at  timestamptz   NOT NULL
);
CREATE INDEX idx_projects_owner ON projects (owner_id);
CREATE INDEX idx_projects_updated ON projects (updated_at DESC);

CREATE TABLE project_members (
    id         uuid        PRIMARY KEY,
    project_id uuid        NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    user_id    uuid        NOT NULL REFERENCES users (id),
    role       varchar(10) NOT NULL,
    joined_at  timestamptz NOT NULL,
    CONSTRAINT uk_project_members UNIQUE (project_id, user_id),
    CONSTRAINT ck_project_members_role CHECK (role IN ('OWNER', 'MEMBER'))
);
CREATE INDEX idx_project_members_user ON project_members (user_id);

CREATE TABLE tasks (
    id          uuid             PRIMARY KEY,
    project_id  uuid             NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    title       varchar(200)     NOT NULL,
    description varchar(5000),
    status      varchar(20)      NOT NULL,
    priority    varchar(10)      NOT NULL DEFAULT 'MEDIUM',
    due_date    date,
    assignee_id uuid             REFERENCES users (id) ON DELETE SET NULL,
    position    double precision NOT NULL,
    created_at  timestamptz      NOT NULL,
    updated_at  timestamptz      NOT NULL,
    CONSTRAINT ck_tasks_status CHECK (status IN ('BACKLOG', 'TODO', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT ck_tasks_priority CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW'))
);
CREATE INDEX idx_tasks_board ON tasks (project_id, status, position, id);
CREATE INDEX idx_tasks_assignee_status ON tasks (assignee_id, status);
CREATE INDEX idx_tasks_status_due ON tasks (status, due_date);

CREATE TABLE tags (
    id         uuid        PRIMARY KEY,
    project_id uuid        NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    name       varchar(30) NOT NULL,
    color      varchar(20) NOT NULL
);
CREATE UNIQUE INDEX uk_tags_project_name ON tags (project_id, lower(name));

CREATE TABLE task_tags (
    task_id uuid NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    tag_id  uuid NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, tag_id)
);
CREATE INDEX idx_task_tags_tag ON task_tags (tag_id);

CREATE TABLE notifications (
    id         uuid         PRIMARY KEY,
    user_id    uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    task_id    uuid         REFERENCES tasks (id) ON DELETE CASCADE,
    project_id uuid         REFERENCES projects (id) ON DELETE CASCADE,
    type       varchar(40)  NOT NULL,
    title      varchar(200) NOT NULL,
    message    varchar(500) NOT NULL,
    is_read    boolean      NOT NULL DEFAULT false,
    created_at timestamptz  NOT NULL,
    dedupe_key varchar(200),
    CONSTRAINT uk_notifications_dedupe UNIQUE (dedupe_key),
    CONSTRAINT ck_notifications_type CHECK (type IN (
        'TASK_ASSIGNED', 'TASK_UNASSIGNED', 'TASK_UPDATED', 'TASK_STATUS_CHANGED',
        'TASK_DEADLINE_APPROACHING', 'TASK_OVERDUE'))
);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC, id DESC);
CREATE INDEX idx_notifications_user_unread ON notifications (user_id) WHERE is_read = false;
CREATE INDEX idx_notifications_task ON notifications (task_id);
CREATE INDEX idx_notifications_project ON notifications (project_id);

-- Activity history survives deletions: references are nulled and the row keeps name snapshots in metadata.
CREATE TABLE activity_logs (
    id          uuid         PRIMARY KEY,
    user_id     uuid         REFERENCES users (id) ON DELETE SET NULL,
    project_id  uuid         REFERENCES projects (id) ON DELETE SET NULL,
    task_id     uuid         REFERENCES tasks (id) ON DELETE SET NULL,
    action      varchar(40)  NOT NULL,
    description varchar(500) NOT NULL,
    metadata    jsonb,
    created_at  timestamptz  NOT NULL,
    CONSTRAINT ck_activity_logs_action CHECK (action IN (
        'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'PROJECT_MEMBER_ADDED', 'PROJECT_MEMBER_REMOVED',
        'TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_ASSIGNED', 'TASK_UNASSIGNED',
        'TASK_STATUS_CHANGED', 'TASK_PRIORITY_CHANGED', 'TASK_DUE_DATE_CHANGED', 'TASK_COMPLETED',
        'USER_ROLE_CHANGED', 'USER_STATUS_CHANGED'))
);
CREATE INDEX idx_activity_logs_created ON activity_logs (created_at DESC, id DESC);
CREATE INDEX idx_activity_logs_project_created ON activity_logs (project_id, created_at DESC);
CREATE INDEX idx_activity_logs_user_created ON activity_logs (user_id, created_at DESC);
CREATE INDEX idx_activity_logs_task ON activity_logs (task_id);
