-- IT Managers can create, edit, reset the password of and delete user accounts; each change is audited.
ALTER TABLE activity_logs DROP CONSTRAINT ck_activity_logs_action;
ALTER TABLE activity_logs ADD CONSTRAINT ck_activity_logs_action CHECK (action IN (
    'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'PROJECT_MEMBER_ADDED', 'PROJECT_MEMBER_REMOVED',
    'TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_ASSIGNED', 'TASK_UNASSIGNED',
    'TASK_STATUS_CHANGED', 'TASK_PRIORITY_CHANGED', 'TASK_DUE_DATE_CHANGED', 'TASK_COMPLETED',
    'USER_CREATED', 'USER_UPDATED', 'USER_ROLE_CHANGED', 'USER_STATUS_CHANGED', 'USER_PASSWORD_RESET',
    'USER_DELETED'));
